/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFramePrincipal.java
 *
 * Created on 25-jun-2010, 11:49:37
 */
package conexionredtrabajo1;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import org.jfree.chart.ChartMouseEvent;
import org.jfree.chart.ChartMouseListener;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.DefaultXYZDataset;
import org.jfree.ui.RectangleEdge;

/**
 *
 * @author Ruben
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private double sombreado_vertical;
    private double sombreado_horizontal;
    private double elevacion;
    private double acimut;

    /** Creates new form JFramePrincipal */
    public JFramePrincipal() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupModoGrafico = new javax.swing.ButtonGroup();
        chartPanelSol = new GraficaPosicionSol();
        dibujarchartPanel = new DibujarChartPanel(chartPanelSol.chart);
        dibujarchartPanel.addChartMouseListener(new ChartMouseListener() {
            public void chartMouseClicked(ChartMouseEvent event) {
                jPanelGraficoMouseClicked(event);
            }
            public void chartMouseMoved(ChartMouseEvent event) {
            }
        });
        jPanelGrafico = dibujarchartPanel;
        jRadioButtonModoLineal = new javax.swing.JRadioButton();
        jRadioButtonModoAguiar = new javax.swing.JRadioButton();
        jButtonArchivoJPG = new javax.swing.JButton();
        jCheckBoxLineasSombra = new javax.swing.JCheckBox();
        jPanelSeparacion = new javax.swing.JPanel();
        jSliderSp = new javax.swing.JSlider();
        jLabelSp = new javax.swing.JLabel();
        jSliderHp = new javax.swing.JSlider();
        jLabelHp = new javax.swing.JLabel();
        jLabelDp = new javax.swing.JLabel();
        jCheckBoxDp = new javax.swing.JCheckBox();
        jLabelTextoHp = new javax.swing.JLabel();
        jLabelTextoSp = new javax.swing.JLabel();
        jPanelOrientacionInclinacion = new javax.swing.JPanel();
        jSliderBeta = new javax.swing.JSlider();
        jLabelBeta = new javax.swing.JLabel();
        jSliderAlfa = new javax.swing.JSlider();
        jLabelAlfa = new javax.swing.JLabel();
        jSliderAlfaFachada = new javax.swing.JSlider();
        jLabelAlfaFachada = new javax.swing.JLabel();
        jSliderLatitud = new javax.swing.JSlider();
        jLabelLatitud = new javax.swing.JLabel();
        jLabelTextoBeta = new javax.swing.JLabel();
        jLabelTextoAlfa = new javax.swing.JLabel();
        jLabelTextoAm1 = new javax.swing.JLabel();
        jLabelTextoAm2 = new javax.swing.JLabel();
        jPanelDimensiones = new javax.swing.JPanel();
        jSliderAm = new javax.swing.JSlider();
        jLabelAm = new javax.swing.JLabel();
        jSliderLm = new javax.swing.JSlider();
        jLabelLm = new javax.swing.JLabel();
        jSliderParteFV = new javax.swing.JSlider();
        jLabelParteFV = new javax.swing.JLabel();
        jLabelTextoLm = new javax.swing.JLabel();
        jLabelTextoParteFV = new javax.swing.JLabel();
        jLabelTextoAm = new javax.swing.JLabel();
        jPanelPuntoSeleccionado = new javax.swing.JPanel();
        jLabelTextoMomento = new javax.swing.JLabel();
        jLabelMomento = new javax.swing.JLabel();
        jPanelDibujo = new DibujarJPanel();
        jLabelTextoPosicionRaton = new javax.swing.JLabel();
        jLabelAcimut = new javax.swing.JLabel();
        jLabelElevacion = new javax.swing.JLabel();
        jLabelTextoSombreado = new javax.swing.JLabel();
        jLabelSombreadoHorizontal = new javax.swing.JLabel();
        jLabelSombreadoVertical = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelTextoEnergiaMomento = new javax.swing.JLabel();
        jLabelEnergiaMomento = new javax.swing.JLabel();
        jPanelEnergiaSombreado = new javax.swing.JPanel();
        jLabelGdm0 = new javax.swing.JLabel();
        jLabelTextoGdm0 = new javax.swing.JLabel();
        jLabelTextoGdm_ab = new javax.swing.JLabel();
        jLabelGdm_ab = new javax.swing.JLabel();
        jLabelTextoSombraFachada = new javax.swing.JLabel();
        jLabelSombraFachada = new javax.swing.JLabel();
        jLabelTextoSombraArea = new javax.swing.JLabel();
        jLabelSombraArea = new javax.swing.JLabel();
        jLabelTextoSombraMaxima = new javax.swing.JLabel();
        jLabelSombraMaxima = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTextoEnergiaDia = new javax.swing.JLabel();
        jLabelEnergiaDia = new javax.swing.JLabel();
        jButtonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Análisis de sombreado mutuo sobre parasoles");

        jPanelGrafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelGrafico.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jPanelGrafico.setPreferredSize(new java.awt.Dimension(800, 570));

        javax.swing.GroupLayout jPanelGraficoLayout = new javax.swing.GroupLayout(jPanelGrafico);
        jPanelGrafico.setLayout(jPanelGraficoLayout);
        jPanelGraficoLayout.setHorizontalGroup(
            jPanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        jPanelGraficoLayout.setVerticalGroup(
            jPanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        buttonGroupModoGrafico.add(jRadioButtonModoLineal);
        jRadioButtonModoLineal.setSelected(true);
        jRadioButtonModoLineal.setText("Modo gráfico Lineal");
        jRadioButtonModoLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonModoLinealActionPerformed(evt);
            }
        });

        buttonGroupModoGrafico.add(jRadioButtonModoAguiar);
        jRadioButtonModoAguiar.setText("Modo gráfico Aguiar");
        jRadioButtonModoAguiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonModoAguiarActionPerformed(evt);
            }
        });

        jButtonArchivoJPG.setText("Genera .jpg");
        jButtonArchivoJPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArchivoJPGActionPerformed(evt);
            }
        });

        jCheckBoxLineasSombra.setSelected(true);
        jCheckBoxLineasSombra.setText("Mostrar líneas sombra");
        jCheckBoxLineasSombra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLineasSombraActionPerformed(evt);
            }
        });

        jPanelSeparacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Separación entre lamas"));

        jSliderSp.setMaximum(200);
        jSliderSp.setValue((int)(Constantes.SP * 10));
        jSliderSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSpStateChanged(evt);
            }
        });

        jLabelSp.setText(Double.toString(jSliderSp.getValue() / 10.0));

        jSliderHp.setMaximum(600);
        jSliderHp.setValue((int)(Constantes.HP * 100));
        jSliderHp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderHpStateChanged(evt);
            }
        });

        jLabelHp.setText(Double.toString(jSliderHp.getValue() / 100.0));

        jLabelDp.setText("(Separación lateral)");

        jCheckBoxDp.setText("Activar Dp");
        jCheckBoxDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDpActionPerformed(evt);
            }
        });

        jLabelTextoHp.setText("Hp:");

        jLabelTextoSp.setText("Sp:");

        javax.swing.GroupLayout jPanelSeparacionLayout = new javax.swing.GroupLayout(jPanelSeparacion);
        jPanelSeparacion.setLayout(jPanelSeparacionLayout);
        jPanelSeparacionLayout.setHorizontalGroup(
            jPanelSeparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeparacionLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelSeparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanelSeparacionLayout.createSequentialGroup()
                        .addComponent(jLabelTextoSp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSp))
                    .addComponent(jSliderSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSeparacionLayout.createSequentialGroup()
                        .addComponent(jCheckBoxDp)
                        .addGap(22, 22, 22)
                        .addComponent(jLabelDp))
                    .addComponent(jSliderHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSeparacionLayout.createSequentialGroup()
                        .addComponent(jLabelTextoHp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHp)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanelSeparacionLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSliderHp, jSliderSp});

        jPanelSeparacionLayout.setVerticalGroup(
            jPanelSeparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeparacionLayout.createSequentialGroup()
                .addComponent(jSliderHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSeparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHp)
                    .addComponent(jLabelTextoHp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSeparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoSp)
                    .addComponent(jLabelSp))
                .addGap(18, 18, 18)
                .addGroup(jPanelSeparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxDp)
                    .addComponent(jLabelDp))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanelSeparacionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSliderHp, jSliderSp});

        jPanelOrientacionInclinacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Orientación e inclinación"));

        jSliderBeta.setMaximum(90);
        jSliderBeta.setValue((int)Constantes.BETA);
        jSliderBeta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderBetaStateChanged(evt);
            }
        });

        jLabelBeta.setText(Integer.toString(jSliderBeta.getValue()));

        jSliderAlfa.setMaximum(180);
        jSliderAlfa.setMinimum(-180);
        jSliderAlfa.setValue((int)Constantes.ALFA);
        jSliderAlfa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAlfaStateChanged(evt);
            }
        });

        jLabelAlfa.setText(Integer.toString(jSliderAlfa.getValue()));

        jSliderAlfaFachada.setMaximum(180);
        jSliderAlfaFachada.setMinimum(-180);
        jSliderAlfaFachada.setValue((int)(Constantes.ALFA_FACHADA));
        jSliderAlfaFachada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAlfaFachadaStateChanged(evt);
            }
        });

        jLabelAlfaFachada.setText(Integer.toString(jSliderAlfaFachada.getValue()));

        jSliderLatitud.setMaximum(50);
        jSliderLatitud.setMinimum(30);
        jSliderLatitud.setValue((int)(Constantes.LATITUD));
        jSliderLatitud.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderLatitudStateChanged(evt);
            }
        });

        jLabelLatitud.setText(Integer.toString(jSliderLatitud.getValue()));

        jLabelTextoBeta.setText("Beta:");

        jLabelTextoAlfa.setText("Alfa:");

        jLabelTextoAm1.setText("Alfa fachada:");

        jLabelTextoAm2.setText("Latitud:");

        javax.swing.GroupLayout jPanelOrientacionInclinacionLayout = new javax.swing.GroupLayout(jPanelOrientacionInclinacion);
        jPanelOrientacionInclinacion.setLayout(jPanelOrientacionInclinacionLayout);
        jPanelOrientacionInclinacionLayout.setHorizontalGroup(
            jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrientacionInclinacionLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabelTextoAlfa, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAlfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(73, 73, 73))
            .addGroup(jPanelOrientacionInclinacionLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrientacionInclinacionLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jSliderAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrientacionInclinacionLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jSliderAlfaFachada, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(jPanelOrientacionInclinacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderBeta, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelOrientacionInclinacionLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabelTextoBeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelBeta))
                    .addComponent(jSliderLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelOrientacionInclinacionLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelTextoAm2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelLatitud)))
                .addGap(44, 44, 44)
                .addComponent(jLabelTextoAm1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAlfaFachada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        jPanelOrientacionInclinacionLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSliderAlfa, jSliderAlfaFachada, jSliderBeta, jSliderLatitud});

        jPanelOrientacionInclinacionLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelBeta, jLabelLatitud});

        jPanelOrientacionInclinacionLayout.setVerticalGroup(
            jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrientacionInclinacionLayout.createSequentialGroup()
                .addGroup(jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrientacionInclinacionLayout.createSequentialGroup()
                        .addComponent(jSliderBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBeta)
                            .addComponent(jLabelTextoBeta)))
                    .addGroup(jPanelOrientacionInclinacionLayout.createSequentialGroup()
                        .addComponent(jSliderAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAlfa)
                            .addComponent(jLabelTextoAlfa))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderAlfaFachada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTextoAm2)
                        .addComponent(jLabelLatitud))
                    .addGroup(jPanelOrientacionInclinacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTextoAm1)
                        .addComponent(jLabelAlfaFachada)))
                .addContainerGap())
        );

        jPanelOrientacionInclinacionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSliderAlfa, jSliderAlfaFachada, jSliderBeta, jSliderLatitud});

        jPanelOrientacionInclinacionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelTextoAlfa, jLabelTextoAm1, jLabelTextoAm2, jLabelTextoBeta});

        jPanelOrientacionInclinacionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelAlfa, jLabelAlfaFachada, jLabelBeta, jLabelLatitud});

        jPanelDimensiones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dimensiones lamas"));

        jSliderAm.setMaximum(200);
        jSliderAm.setValue((int) (Constantes.AM * 10));
        jSliderAm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAmStateChanged(evt);
            }
        });

        jLabelAm.setText(Double.toString(jSliderAm.getValue() / 10.0));

        jSliderLm.setMaximum(200);
        jSliderLm.setValue((int)(Constantes.LM * 100));
        jSliderLm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderLmStateChanged(evt);
            }
        });

        jLabelLm.setText(Double.toString(jSliderLm.getValue() / 100.0));

        jSliderParteFV.setValue((int)(Constantes.porcentaje_con_FV));
        jSliderParteFV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderParteFVStateChanged(evt);
            }
        });

        jLabelParteFV.setText(Integer.toString(jSliderParteFV.getValue()));

        jLabelTextoLm.setText("Lm:");

        jLabelTextoParteFV.setText("%FV:");

        jLabelTextoAm.setText("Am:");

        javax.swing.GroupLayout jPanelDimensionesLayout = new javax.swing.GroupLayout(jPanelDimensiones);
        jPanelDimensiones.setLayout(jPanelDimensionesLayout);
        jPanelDimensionesLayout.setHorizontalGroup(
            jPanelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDimensionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSliderAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderParteFV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderLm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDimensionesLayout.createSequentialGroup()
                        .addComponent(jLabelTextoAm)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAm))
                    .addGroup(jPanelDimensionesLayout.createSequentialGroup()
                        .addComponent(jLabelTextoLm)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLm))
                    .addGroup(jPanelDimensionesLayout.createSequentialGroup()
                        .addComponent(jLabelTextoParteFV)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelParteFV)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanelDimensionesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSliderAm, jSliderLm, jSliderParteFV});

        jPanelDimensionesLayout.setVerticalGroup(
            jPanelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDimensionesLayout.createSequentialGroup()
                .addComponent(jSliderLm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoLm)
                    .addComponent(jLabelLm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderParteFV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoParteFV)
                    .addComponent(jLabelParteFV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoAm)
                    .addComponent(jLabelAm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDimensionesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSliderAm, jSliderLm, jSliderParteFV});

        jPanelPuntoSeleccionado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Punto solar seleccionado"));

        jLabelTextoMomento.setText("Momento seleccionado (días, hora):");

        jLabelMomento.setText("días hh:mm");

        jPanelDibujo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDibujo.setPreferredSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanelDibujoLayout = new javax.swing.GroupLayout(jPanelDibujo);
        jPanelDibujo.setLayout(jPanelDibujoLayout);
        jPanelDibujoLayout.setHorizontalGroup(
            jPanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        jPanelDibujoLayout.setVerticalGroup(
            jPanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        jLabelTextoPosicionRaton.setText("Posición Sol (elevación, acimut):");

        jLabelAcimut.setText("Acimut");

        jLabelElevacion.setText("Elevación");

        jLabelTextoSombreado.setText("Sombreado lama (%Sv, %Sh):");

        jLabelSombreadoHorizontal.setText("%Sh");

        jLabelSombreadoVertical.setText("%Sv");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelTextoEnergiaMomento.setText("<html>Energía instantánea<p>(Wh/m2)");

        jLabelEnergiaMomento.setText("Wh");

        javax.swing.GroupLayout jPanelPuntoSeleccionadoLayout = new javax.swing.GroupLayout(jPanelPuntoSeleccionado);
        jPanelPuntoSeleccionado.setLayout(jPanelPuntoSeleccionadoLayout);
        jPanelPuntoSeleccionadoLayout.setHorizontalGroup(
            jPanelPuntoSeleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPuntoSeleccionadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPuntoSeleccionadoLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanelPuntoSeleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPuntoSeleccionadoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelSombreadoVertical)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSombreadoHorizontal))
                    .addComponent(jLabelTextoPosicionRaton)
                    .addComponent(jLabelTextoSombreado)
                    .addComponent(jLabelTextoMomento)
                    .addGroup(jPanelPuntoSeleccionadoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelElevacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAcimut))
                    .addGroup(jPanelPuntoSeleccionadoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelMomento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPuntoSeleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTextoEnergiaMomento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEnergiaMomento))
                .addGap(46, 46, 46))
        );
        jPanelPuntoSeleccionadoLayout.setVerticalGroup(
            jPanelPuntoSeleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPuntoSeleccionadoLayout.createSequentialGroup()
                .addGroup(jPanelPuntoSeleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPuntoSeleccionadoLayout.createSequentialGroup()
                        .addComponent(jLabelTextoPosicionRaton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPuntoSeleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPuntoSeleccionadoLayout.createSequentialGroup()
                                .addGroup(jPanelPuntoSeleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelElevacion)
                                    .addComponent(jLabelAcimut))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTextoMomento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMomento)
                                .addGap(12, 12, 12)
                                .addComponent(jLabelTextoSombreado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelPuntoSeleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelSombreadoHorizontal)
                                    .addComponent(jLabelSombreadoVertical)))
                            .addGroup(jPanelPuntoSeleccionadoLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabelTextoEnergiaMomento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEnergiaMomento))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEnergiaSombreado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Energías y sombreados anuales"));

        DecimalFormat formateador = new DecimalFormat("0.00");
        jLabelGdm0.setText(formateador.format((chartPanelSol.radiacion_anual_horizontal / 365 / 1000)));

        jLabelTextoGdm0.setText("Gdm0 (kWh/m2/día):");

        jLabelTextoGdm_ab.setText("Gdm_ab (kWh/m2/día):");

        jLabelGdm_ab.setText(formateador.format(chartPanelSol.radiacion_anual / 365 / 1000));

        jLabelTextoSombraFachada.setText("% sombra fachada:");

        DecimalFormat formateador_porcentaje = new DecimalFormat("#0.0%");
        jLabelSombraFachada.setText(formateador_porcentaje.format(chartPanelSol.sombreado_anual_fachada / chartPanelSol.radiacion_anual));

        jLabelTextoSombraArea.setText("% sombra área:");

        jLabelSombraArea.setText(formateador_porcentaje.format(chartPanelSol.sombreado_anual_mutuo_area / chartPanelSol.radiacion_anual));

        jLabelTextoSombraMaxima.setText("% sombra máxima:");

        jLabelSombraMaxima.setText(formateador_porcentaje.format(chartPanelSol.sombreado_anual_mutuo_maximo / chartPanelSol.radiacion_anual));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelTextoEnergiaDia.setText("<html>Energía media<p>(kWh/m2/día)");

        jLabelEnergiaDia.setText(formateador.format((chartPanelSol.radiacion_anual - chartPanelSol.sombreado_anual_fachada - chartPanelSol.sombreado_anual_mutuo_maximo) / 365 / 1000));

        javax.swing.GroupLayout jPanelEnergiaSombreadoLayout = new javax.swing.GroupLayout(jPanelEnergiaSombreado);
        jPanelEnergiaSombreado.setLayout(jPanelEnergiaSombreadoLayout);
        jPanelEnergiaSombreadoLayout.setHorizontalGroup(
            jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnergiaSombreadoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnergiaSombreadoLayout.createSequentialGroup()
                        .addComponent(jLabelTextoSombraMaxima, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSombraMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnergiaSombreadoLayout.createSequentialGroup()
                        .addComponent(jLabelTextoSombraArea, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSombraArea, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnergiaSombreadoLayout.createSequentialGroup()
                        .addGroup(jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEnergiaSombreadoLayout.createSequentialGroup()
                                .addComponent(jLabelTextoSombraFachada, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jLabelTextoGdm_ab, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabelTextoGdm0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGroup(jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelSombraFachada, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabelGdm_ab, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabelGdm0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTextoEnergiaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEnergiaDia))
                .addGap(63, 63, 63))
        );
        jPanelEnergiaSombreadoLayout.setVerticalGroup(
            jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnergiaSombreadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEnergiaSombreadoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelTextoEnergiaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEnergiaDia))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEnergiaSombreadoLayout.createSequentialGroup()
                        .addGroup(jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGdm0)
                            .addComponent(jLabelTextoGdm0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGdm_ab)
                            .addComponent(jLabelTextoGdm_ab))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSombraFachada)
                            .addComponent(jLabelTextoSombraFachada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSombraArea)
                            .addComponent(jLabelTextoSombraArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnergiaSombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSombraMaxima)
                            .addComponent(jLabelTextoSombraMaxima))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelEnergiaSombreado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelPuntoSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonModoAguiar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonModoLineal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                                .addComponent(jButtonArchivoJPG))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSeparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jPanelDimensiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxLineasSombra))
                            .addComponent(jPanelOrientacionInclinacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelGrafico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelEnergiaSombreado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPuntoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                                .addComponent(jRadioButtonModoLineal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonModoAguiar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonArchivoJPG)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelSeparacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanelOrientacionInclinacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jCheckBoxLineasSombra))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonActualizar))))
                        .addComponent(jPanelDimensiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelOrientacionInclinacion.getAccessibleContext().setAccessibleName("Orientación e inclinación (º)");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderBetaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderBetaStateChanged
        jLabelBeta.setText(Integer.toString(jSliderBeta.getValue()));
    }//GEN-LAST:event_jSliderBetaStateChanged

    private void jSliderLatitudStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderLatitudStateChanged
        jLabelLatitud.setText(Integer.toString(jSliderLatitud.getValue()));
    }//GEN-LAST:event_jSliderLatitudStateChanged

    private void jRadioButtonModoLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonModoLinealActionPerformed
        Constantes.GRAFICO_AGUIAR = false;

        jButtonActualizar.doClick();
    }//GEN-LAST:event_jRadioButtonModoLinealActionPerformed

    private void jRadioButtonModoAguiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonModoAguiarActionPerformed
        Constantes.GRAFICO_AGUIAR = true;

        jButtonActualizar.doClick();
    }//GEN-LAST:event_jRadioButtonModoAguiarActionPerformed

    private void jButtonArchivoJPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArchivoJPGActionPerformed
        try {
            String nombre = "-lat_" + Double.toString(Constantes.LATITUD) + "-beta_" + Double.toString(Constantes.BETA) + "-alfa_" + Double.toString(Constantes.ALFA) + "-Sp_" + Double.toString(Constantes.SP) + "-Lm_" + Double.toString(Constantes.LM) + "-%FV_" + Double.toString(Constantes.porcentaje_con_FV) + "-Am_" + Double.toString(Constantes.AM);
            ChartUtilities.saveChartAsJPEG(new File("/" + nombre + ".jpg"), chartPanelSol.chart, 1000, 600);
            JOptionPane.showMessageDialog(null, "Archivo " + nombre + " generado!", "Archivo OK", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.out.println("Error al crear archivo .jpg");
        } catch (HeadlessException ex1) {
            System.out.println("Error al crear ventana");
        }
    }//GEN-LAST:event_jButtonArchivoJPGActionPerformed

    private void jCheckBoxLineasSombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLineasSombraActionPerformed
        if (jCheckBoxLineasSombra.isSelected()) {
            Constantes.LINEAS_SOMBRA = true;
        } else {
            Constantes.LINEAS_SOMBRA = false;
        }

        jButtonActualizar.doClick();
    }//GEN-LAST:event_jCheckBoxLineasSombraActionPerformed

    private void jSliderAlfaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAlfaStateChanged
        jLabelAlfa.setText(Integer.toString(jSliderAlfa.getValue()));
    }//GEN-LAST:event_jSliderAlfaStateChanged

    private void jSliderAlfaFachadaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAlfaFachadaStateChanged
        jLabelAlfaFachada.setText(Integer.toString(jSliderAlfaFachada.getValue()));
    }//GEN-LAST:event_jSliderAlfaFachadaStateChanged

    private void jSliderHpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderHpStateChanged
        jLabelHp.setText(Double.toString(jSliderHp.getValue() / 100.0));
    }//GEN-LAST:event_jSliderHpStateChanged

    private void jSliderSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSpStateChanged
        jLabelSp.setText(Double.toString(jSliderSp.getValue() / 10.0));
    }//GEN-LAST:event_jSliderSpStateChanged

    private void jSliderAmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAmStateChanged
        jLabelAm.setText(Double.toString(jSliderAm.getValue() / 10.0));
    }//GEN-LAST:event_jSliderAmStateChanged

    private void jSliderLmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderLmStateChanged
        jLabelLm.setText(Double.toString(jSliderLm.getValue() / 100.0));
    }//GEN-LAST:event_jSliderLmStateChanged

    private void jSliderParteFVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderParteFVStateChanged
        jLabelParteFV.setText(Integer.toString(jSliderParteFV.getValue()));
    }//GEN-LAST:event_jSliderParteFVStateChanged

    private void jCheckBoxDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDpActionPerformed
        if (jCheckBoxDp.isSelected()) {
            Constantes.DP = Constantes.SP * Math.tan(Math.toRadians(Constantes.ALFA_FACHADA - Constantes.ALFA));
            DecimalFormat formateador = new DecimalFormat("0.00");
            jLabelDp.setText(formateador.format(Constantes.DP));
        } else {
            Constantes.DP = 0;
            jLabelDp.setText("(Separación lateral)");
        }

        jButtonActualizar.doClick();
    }//GEN-LAST:event_jCheckBoxDpActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        Constantes.BETA = Double.parseDouble(jLabelBeta.getText());
        Constantes.LATITUD = Double.parseDouble(jLabelLatitud.getText());
        Constantes.ALFA = Double.parseDouble(jLabelAlfa.getText());
        Constantes.ALFA_FACHADA = Double.parseDouble(jLabelAlfaFachada.getText());

        Constantes.HP = Double.parseDouble(jLabelHp.getText());
        Constantes.SP = Double.parseDouble(jLabelSp.getText());

        if (jCheckBoxDp.isSelected()) {
            Constantes.DP = Constantes.SP * Math.tan(Math.toRadians(Constantes.ALFA_FACHADA - Constantes.ALFA));
            DecimalFormat formateador = new DecimalFormat("0.00");
            jLabelDp.setText(formateador.format(Constantes.DP));
        }

        Constantes.AM = Double.parseDouble(jLabelAm.getText());
        Constantes.LM = Double.parseDouble(jLabelLm.getText());
        Constantes.porcentaje_con_FV = Double.parseDouble(jLabelParteFV.getText());
        Constantes.LM_FV = Constantes.LM * (Constantes.porcentaje_con_FV / 100.0);

        chartPanelSol = new GraficaPosicionSol();
        dibujarchartPanel.setChart(chartPanelSol.chart);
        jPanelGrafico = dibujarchartPanel;

        DecimalFormat formateador = new DecimalFormat("0.00");

        jLabelGdm0.setText(formateador.format(chartPanelSol.radiacion_anual_horizontal / 365 / 1000));
        jLabelGdm_ab.setText(formateador.format(chartPanelSol.radiacion_anual / 365 / 1000));

        DecimalFormat formateador_porcentaje = new DecimalFormat("#0.0%");

        jLabelSombraFachada.setText(formateador_porcentaje.format(chartPanelSol.sombreado_anual_fachada / chartPanelSol.radiacion_anual));
        jLabelSombraArea.setText(formateador_porcentaje.format(chartPanelSol.sombreado_anual_mutuo_area / chartPanelSol.radiacion_anual));
        jLabelSombraMaxima.setText(formateador_porcentaje.format(chartPanelSol.sombreado_anual_mutuo_maximo / chartPanelSol.radiacion_anual));

        jLabelEnergiaDia.setText(formateador.format((chartPanelSol.radiacion_anual - chartPanelSol.sombreado_anual_fachada - chartPanelSol.sombreado_anual_mutuo_maximo) / 365 / 1000));
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jPanelGraficoMouseClicked(ChartMouseEvent event) {
        int mouseX = event.getTrigger().getX();
        int mouseY = event.getTrigger().getY();

        posicion_raton.setLocation(mouseX, mouseY);

        Point2D punto = dibujarchartPanel.translateScreenToJava2D(new Point(mouseX, mouseY));
        XYPlot plot = (XYPlot) dibujarchartPanel.getChart().getPlot();
        Rectangle2D plotArea = dibujarchartPanel.getScreenDataArea();

        ValueAxis domainAxis = plot.getDomainAxis();
        RectangleEdge domainAxisEdge = plot.getDomainAxisEdge();
        ValueAxis rangeAxis = plot.getRangeAxis();
        RectangleEdge rangeAxisEdge = plot.getRangeAxisEdge();

        elevacion = domainAxis.java2DToValue(punto.getX(), plotArea, domainAxisEdge);
        acimut = rangeAxis.java2DToValue(punto.getY(), plotArea, rangeAxisEdge);

        DecimalFormat formateador = new DecimalFormat("00");
        jLabelElevacion.setText(formateador.format(acimut));
        jLabelAcimut.setText(formateador.format(elevacion));

        DecimalFormat formateador_porcentaje = new DecimalFormat("00%");
        sombreado_vertical = GraficaPosicionSol.PorcentajeSombreadoVertical(elevacion, acimut);
        sombreado_horizontal = GraficaPosicionSol.PorcentajeSombreadoHorizontal(elevacion, acimut);

        jLabelSombreadoVertical.setText(formateador_porcentaje.format(sombreado_vertical / 100));
        jLabelSombreadoHorizontal.setText(formateador_porcentaje.format(sombreado_horizontal / 100));
        if (sombreado_horizontal > 100.0) {
            jLabelSombreadoHorizontal.setText(formateador_porcentaje.format((200 - GraficaPosicionSol.PorcentajeSombreadoHorizontal(elevacion, acimut)) / 100));
        }

        String hora = formateador.format(Math.floor(GraficaPosicionSol.HoraSol(elevacion, acimut))) + ":" + formateador.format(Math.floor((GraficaPosicionSol.HoraSol(elevacion, acimut) - Math.floor(GraficaPosicionSol.HoraSol(elevacion, acimut))) * 60));
        String dias;

        if (java.lang.Double.isNaN(GraficaPosicionSol.DiaSol(elevacion, acimut))) {
            dias = "---";
        } else {
            GregorianCalendar calendario = new GregorianCalendar();
            calendario.set(GregorianCalendar.DAY_OF_YEAR, (int) Math.rint(GraficaPosicionSol.DiaSol(elevacion, acimut)));
            int dia1 = calendario.get(GregorianCalendar.DAY_OF_MONTH);
            int mes1 = calendario.get(GregorianCalendar.MONTH) + 1;

            calendario.set(GregorianCalendar.DAY_OF_YEAR, (int) Math.rint(172 - GraficaPosicionSol.DiaSol(elevacion, acimut) + 172));
            int dia2 = calendario.get(GregorianCalendar.DAY_OF_MONTH);
            int mes2 = calendario.get(GregorianCalendar.MONTH) + 1;

            dias = dia1 + "/" + mes1 + " y " + dia2 + "/" + mes2;
        }
        jLabelMomento.setText(dias + ", " + hora);

        jLabelEnergiaMomento.setText(formateador.format(((DefaultXYZDataset) chartPanelSol.chart.getXYPlot().getDataset(1)).getZValue((int) Math.rint(GraficaPosicionSol.DiaSol(elevacion, acimut)), (int) ((GraficaPosicionSol.HoraSol(elevacion, acimut) + 12) * DatosSolMomento.MOM_HORA))));
        System.out.println("dia: " + (int) Math.rint(GraficaPosicionSol.DiaSol(elevacion, acimut)) + "hora: " + (int) ((GraficaPosicionSol.HoraSol(elevacion, acimut) + 12) * DatosSolMomento.MOM_HORA));

        jPanelDibujo.repaint();
        jPanelGrafico.repaint();
    }

    class DibujarJPanel extends JPanel {

        @Override
        public void paintComponent(Graphics grafico) {
            super.paintComponent(grafico);

            if (java.lang.Double.isNaN(GraficaPosicionSol.DiaSol(elevacion, acimut))) {
                grafico.fillRect(0, 0, 0, 0);
            } else {
                grafico.setColor(Color.gray);
                if (sombreado_horizontal < 100.0) {
                    grafico.fillRect(0, 0, this.getWidth() * (int) sombreado_horizontal / 100, this.getHeight() * (int) sombreado_vertical / 100);
                } else {
                    grafico.fillRect(-1 * (this.getWidth() - this.getWidth() * (int) sombreado_horizontal / 100), 0, this.getWidth() * (int) sombreado_horizontal / 100, this.getHeight() * (int) sombreado_vertical / 100);
                }
            }
        }
    }

    public class DibujarChartPanel extends ChartPanel {

        private DibujarChartPanel(JFreeChart chart) {
            super(chart);
        }

        @Override
        public void paintComponent(Graphics grafico) {
            super.paintComponent(grafico);

            grafico.setColor(Color.red);

//            grafico.drawRect(posicion_raton.x - 3, posicion_raton.y - 3, 6, 6);
            grafico.drawLine(posicion_raton.x - 3, posicion_raton.y - 3, posicion_raton.x + 3, posicion_raton.y + 3);
            grafico.drawLine(posicion_raton.x + 3, posicion_raton.y - 3, posicion_raton.x - 3, posicion_raton.y + 3);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }
    private Point posicion_raton = new Point(0, 0);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupModoGrafico;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonArchivoJPG;
    private javax.swing.JCheckBox jCheckBoxDp;
    private javax.swing.JCheckBox jCheckBoxLineasSombra;
    private javax.swing.JLabel jLabelAcimut;
    private javax.swing.JLabel jLabelAlfa;
    private javax.swing.JLabel jLabelAlfaFachada;
    private javax.swing.JLabel jLabelAm;
    private javax.swing.JLabel jLabelBeta;
    private javax.swing.JLabel jLabelDp;
    private javax.swing.JLabel jLabelElevacion;
    private javax.swing.JLabel jLabelEnergiaDia;
    private javax.swing.JLabel jLabelEnergiaMomento;
    private javax.swing.JLabel jLabelGdm0;
    private javax.swing.JLabel jLabelGdm_ab;
    private javax.swing.JLabel jLabelHp;
    private javax.swing.JLabel jLabelLatitud;
    private javax.swing.JLabel jLabelLm;
    private javax.swing.JLabel jLabelMomento;
    private javax.swing.JLabel jLabelParteFV;
    private javax.swing.JLabel jLabelSombraArea;
    private javax.swing.JLabel jLabelSombraFachada;
    private javax.swing.JLabel jLabelSombraMaxima;
    private javax.swing.JLabel jLabelSombreadoHorizontal;
    private javax.swing.JLabel jLabelSombreadoVertical;
    private javax.swing.JLabel jLabelSp;
    private javax.swing.JLabel jLabelTextoAlfa;
    private javax.swing.JLabel jLabelTextoAm;
    private javax.swing.JLabel jLabelTextoAm1;
    private javax.swing.JLabel jLabelTextoAm2;
    private javax.swing.JLabel jLabelTextoBeta;
    private javax.swing.JLabel jLabelTextoEnergiaDia;
    private javax.swing.JLabel jLabelTextoEnergiaMomento;
    private javax.swing.JLabel jLabelTextoGdm0;
    private javax.swing.JLabel jLabelTextoGdm_ab;
    private javax.swing.JLabel jLabelTextoHp;
    private javax.swing.JLabel jLabelTextoLm;
    private javax.swing.JLabel jLabelTextoMomento;
    private javax.swing.JLabel jLabelTextoParteFV;
    private javax.swing.JLabel jLabelTextoPosicionRaton;
    private javax.swing.JLabel jLabelTextoSombraArea;
    private javax.swing.JLabel jLabelTextoSombraFachada;
    private javax.swing.JLabel jLabelTextoSombraMaxima;
    private javax.swing.JLabel jLabelTextoSombreado;
    private javax.swing.JLabel jLabelTextoSp;
    private javax.swing.JPanel jPanelDibujo;
    private javax.swing.JPanel jPanelDimensiones;
    private javax.swing.JPanel jPanelEnergiaSombreado;
    private javax.swing.JPanel jPanelGrafico;
    DibujarChartPanel dibujarchartPanel;
    GraficaPosicionSol chartPanelSol;
    private javax.swing.JPanel jPanelOrientacionInclinacion;
    private javax.swing.JPanel jPanelPuntoSeleccionado;
    private javax.swing.JPanel jPanelSeparacion;
    private javax.swing.JRadioButton jRadioButtonModoAguiar;
    private javax.swing.JRadioButton jRadioButtonModoLineal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSliderAlfa;
    private javax.swing.JSlider jSliderAlfaFachada;
    private javax.swing.JSlider jSliderAm;
    private javax.swing.JSlider jSliderBeta;
    private javax.swing.JSlider jSliderHp;
    private javax.swing.JSlider jSliderLatitud;
    private javax.swing.JSlider jSliderLm;
    private javax.swing.JSlider jSliderParteFV;
    private javax.swing.JSlider jSliderSp;
    // End of variables declaration//GEN-END:variables
}
